import type { Metadata } from "next";

export const links = {
  sourceCode: "https://github.com",
  ownerName: "Galang",
  ownerEmail: "ardiangalang05@gmail.com",
} as const;

export const siteConfig: Metadata = {
  title: `${links.ownerName}'s Portfolio`,
  description: "Modern & Minimalist Next.js Portfolio.",
  keywords: [
       "javascript",
       "typescript",
       "nodejs",
       "react",
       "nextjs",
       "reactnative",
       "expressjs",
       "nestjs",
       "enterprise-solutions",
       "digital-transformation",
       "ecommerce",
       "erp-systems",
       "cooperative-systems",
       "digital-banking",
       "fintech",
       "point-of-sale",
       "fullstack-development",
       "web-development",
       "mobile-development",
       "api-development",
       "system-architecture",
       "microservices",
       "oauth2",
       "authentication",
       "high-performance",
       "scalable-systems",
       "system-optimization",
       "seo-optimization",
       "page-speed-optimization",
       "user-experience",
       "responsive-design",
       "tailwindcss",
       "material-ui",
       "shadcn-ui",
       "framer-motion",
       "git",
       "gitlab",
       "docker",
       "aws",
       "vercel",
       "agile",
       "clean-code",
       "micro-frontends",
       "test-driven-development",
       "travel-technology",
       "inventory-management",
       "accounting-systems",
       "database-design",
       "api-architecture",
       "performance-optimization",
       "code-refactoring",
       "legacy-system-modernization"
  ] as Array<string>,
  authors: {
    name: links.ownerName,
    url: "https://github.com/neuthos",
  },
} as const;
